from library import Library
from book import Book
import copy

def library_test():
    print("Welcome to the Library Test Module")
    print("==================================")
    print("")
    print("Testing Library Constructor")
    print("")
    master_test_library = Library()
    print("")
    print("==================================")
    print("Testing Library add_book Method")
    print("")
    test_library1 = copy.deepcopy(master_test_library)
    test_library1.add_book(Book("The Alchemist", "Paulo Coelho", "1988", "Adventure/Philosophical", 9780061122415, 1))
    print(test_library1)
    print("==================================")
    test_library2 = copy.deepcopy(master_test_library)
    print("Testing Library remove Method")
    print("")
    test_book1 = Book("The Alchemist", "Paulo Coelho", "1988", "Adventure/Philosophical", 9780061122415, 1, False)
    test_book2 = Book("The Shadow of the Wind", "Carlos Ruiz Zafón", "2001", "Mystery / Historical Fiction", 9780143034908, 2, False)
    test_book3 = Book("Project Hail Mary", "Andy Weir", "2021", "Science Fiction", 9780593135204, 3, False)
    test_library2.add_book(test_book1)
    test_library2.add_book(test_book2)
    test_library2.add_book(test_book3)
    print("Printing Library to Ensure Population")
    print(test_library2)
    print("===================================")
    print(f"Removing Book {test_book1}")
    test_library2.remove_book(test_book1)
    print(f"Printing Library to Ensure Proper Removal")
    print(test_library2)
    print("==================================")
    print("Testing Library Modify Method")
    print("")
    test_library3 = copy.deepcopy(master_test_library)
    test_book4 = Book("The Alchemist", "Paulo Coelho", "1988", "Adventure/Philosophical", 9780061122415, 1, False)
    test_book5 = Book("The Shadow of the Wind", "Carlos Ruiz Zafón", "2001", "Mystery / Historical Fiction", 9780143034908, 2, False)
    test_book6 = Book("Project Hail Mary", "Andy Weir", "2021", "Science Fiction", 9780593135204, 3, False)
    test_library3.add_book(test_book4)
    test_library3.add_book(test_book5)
    test_library3.add_book(test_book6)
    print("Printing Libarary to Ensure Population")
    print(test_library3)
    test_library3.modify_book(test_book1, "Mod Title", "Mod Author", "Mod_date", "Mod genre", 98765432110, True)
    test_library3.modify_book(test_book3, "Mod Title 2", "Mod Author 2", "Mod Date 3", "Mod Genre 2", 12345678920, True)
    print("Printing Modified Library to Ensure Proper Modification")
    print(test_library3)
    print("==================================")
    print("Testing Library Search Method")
    print("")
    test_library4 = copy.deepcopy(master_test_library)
    test_book7 = Book("The Alchemist", "Paulo Coelho", "1988", "Adventure/Philosophical", 9780061122415, 1, False)
    test_book8 = Book("The Shadow of the Wind", "Carlos Ruiz Zafón", "2001", "Mystery / Historical Fiction", 9780143034908, 2, False)
    test_book9 = Book("Project Hail Mary", "Andy Weir", "2021", "Science Fiction", 9780593135204, 3, False)
    test_library4.add_book(test_book7)
    test_library4.add_book(test_book8)
    test_library4.add_book(test_book9)
    print(test_library4.search_library("The Alchemist")[0])
    print(test_library4.search_library("Andy Weir")[0])
    print(test_library4.search_library("2001")[0])
    print(test_library4.search_library("Adventure/Philosophical")[0])
    print(test_library4.search_library(9780061122415)[0])
    print(test_library4.search_library(False))
    print("===================================")
    



    

library_test()